/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SoccerManagermentUIdelegate;
import java.sql.*;
import SoccerManagementDTO.*;
import SoccerManagementModel.*;
import static SoccerManagermentUIdelegate.HomePage.idtour;
import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author Administrator
 */
public class ClubPage extends javax.swing.JFrame {

    /**
     * Creates new form ClubPage
     */
    public static int idCLB;
    ListPlayer listPL= new ListPlayer();
    public ClubPage(int clbid) {
        idCLB=clbid;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        LoadPlayer(clbid);
        LoadClubOverview(clbid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pannelOverview = new javax.swing.JPanel();
        panelSumari = new javax.swing.JPanel();
        panelMember = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMember = new javax.swing.JLabel();
        panelST = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblST = new javax.swing.JLabel();
        panelGoal = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblGoal = new javax.swing.JLabel();
        panelSBT = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblSBT = new javax.swing.JLabel();
        panelYellow = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblYellow = new javax.swing.JLabel();
        panelRed = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblRed = new javax.swing.JLabel();
        panelMostGoal = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblMVP = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblCard = new javax.swing.JLabel();
        lblMostCard = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblLoGo = new javax.swing.JLabel();
        pannelPlayer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnInsertImage = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        DateBorn = new com.toedter.calendar.JDateChooser();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlayer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        pannelOverview.setBackground(new java.awt.Color(255, 255, 255));

        panelSumari.setBackground(new java.awt.Color(255, 255, 255));

        panelMember.setBackground(new java.awt.Color(0, 153, 153));
        panelMember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/member.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Members");

        lblMember.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        lblMember.setForeground(new java.awt.Color(255, 255, 255));
        lblMember.setText("0");

        javax.swing.GroupLayout panelMemberLayout = new javax.swing.GroupLayout(panelMember);
        panelMember.setLayout(panelMemberLayout);
        panelMemberLayout.setHorizontalGroup(
            panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMemberLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelMemberLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMember)))
                .addContainerGap())
        );
        panelMemberLayout.setVerticalGroup(
            panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMemberLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblMember))
                .addContainerGap())
        );

        panelST.setBackground(new java.awt.Color(255, 102, 102));
        panelST.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setBackground(new java.awt.Color(204, 204, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/ST.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Matches");

        lblST.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        lblST.setForeground(new java.awt.Color(255, 255, 255));
        lblST.setText("0");

        javax.swing.GroupLayout panelSTLayout = new javax.swing.GroupLayout(panelST);
        panelST.setLayout(panelSTLayout);
        panelSTLayout.setHorizontalGroup(
            panelSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSTLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblST))
            .addGroup(panelSTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSTLayout.setVerticalGroup(
            panelSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSTLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(panelSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblST))
                .addContainerGap())
        );

        panelGoal.setBackground(new java.awt.Color(102, 255, 102));
        panelGoal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/BT.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Goals");

        lblGoal.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        lblGoal.setForeground(new java.awt.Color(255, 255, 255));
        lblGoal.setText("0");

        javax.swing.GroupLayout panelGoalLayout = new javax.swing.GroupLayout(panelGoal);
        panelGoal.setLayout(panelGoalLayout);
        panelGoalLayout.setHorizontalGroup(
            panelGoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGoalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGoal)
                .addContainerGap())
            .addGroup(panelGoalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGoalLayout.setVerticalGroup(
            panelGoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGoalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(panelGoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblGoal))
                .addContainerGap())
        );

        panelSBT.setBackground(new java.awt.Color(102, 255, 204));
        panelSBT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/SBT.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Concede");

        lblSBT.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        lblSBT.setForeground(new java.awt.Color(255, 255, 255));
        lblSBT.setText("0");

        javax.swing.GroupLayout panelSBTLayout = new javax.swing.GroupLayout(panelSBT);
        panelSBT.setLayout(panelSBTLayout);
        panelSBTLayout.setHorizontalGroup(
            panelSBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSBTLayout.createSequentialGroup()
                .addGroup(panelSBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSBTLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelSBTLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSBT)))
                .addContainerGap())
        );
        panelSBTLayout.setVerticalGroup(
            panelSBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSBTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblSBT))
                .addContainerGap())
        );

        panelYellow.setBackground(new java.awt.Color(255, 204, 153));
        panelYellow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/slyellow.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Yellow card");

        lblYellow.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        lblYellow.setForeground(new java.awt.Color(255, 255, 255));
        lblYellow.setText("0");

        javax.swing.GroupLayout panelYellowLayout = new javax.swing.GroupLayout(panelYellow);
        panelYellow.setLayout(panelYellowLayout);
        panelYellowLayout.setHorizontalGroup(
            panelYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblYellow)
                .addContainerGap())
            .addGroup(panelYellowLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelYellowLayout.setVerticalGroup(
            panelYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(panelYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblYellow))
                .addContainerGap())
        );

        panelRed.setBackground(new java.awt.Color(255, 153, 255));
        panelRed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/slred.png"))); // NOI18N
        jLabel20.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Red card");

        lblRed.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        lblRed.setForeground(new java.awt.Color(255, 255, 255));
        lblRed.setText("0");

        javax.swing.GroupLayout panelRedLayout = new javax.swing.GroupLayout(panelRed);
        panelRed.setLayout(panelRedLayout);
        panelRedLayout.setHorizontalGroup(
            panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedLayout.createSequentialGroup()
                .addGroup(panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRed)))
                .addContainerGap())
        );
        panelRedLayout.setVerticalGroup(
            panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblRed))
                .addContainerGap())
        );

        panelMostGoal.setBackground(new java.awt.Color(153, 255, 153));
        panelMostGoal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel24.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Best Scorer");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/mvp.png"))); // NOI18N

        lblScore.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setText("0");

        lblMVP.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblMVP.setForeground(new java.awt.Color(255, 51, 51));
        lblMVP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMVP.setText("   ");

        javax.swing.GroupLayout panelMostGoalLayout = new javax.swing.GroupLayout(panelMostGoal);
        panelMostGoal.setLayout(panelMostGoalLayout);
        panelMostGoalLayout.setHorizontalGroup(
            panelMostGoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostGoalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblScore)
                .addContainerGap())
            .addComponent(lblMVP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMostGoalLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMostGoalLayout.setVerticalGroup(
            panelMostGoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostGoalLayout.createSequentialGroup()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMVP)
                .addGap(18, 18, 18)
                .addGroup(panelMostGoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblScore))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/mostcard.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Most card");

        lblCard.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        lblCard.setForeground(new java.awt.Color(255, 255, 255));
        lblCard.setText("0");

        lblMostCard.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblMostCard.setForeground(new java.awt.Color(0, 255, 255));
        lblMostCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostCard.setText("   ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(lblCard)
                .addContainerGap())
            .addComponent(lblMostCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblCard))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSumariLayout = new javax.swing.GroupLayout(panelSumari);
        panelSumari.setLayout(panelSumariLayout);
        panelSumariLayout.setHorizontalGroup(
            panelSumariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSumariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSumariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSumariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelGoal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelYellow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMostGoal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelSumariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSumariLayout.setVerticalGroup(
            panelSumariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSumariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSumariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSumariLayout.createSequentialGroup()
                        .addComponent(panelMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSumariLayout.createSequentialGroup()
                        .addGroup(panelSumariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelGoal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelSBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelSumariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelYellow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(panelSumariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelMostGoal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Man United");

        lblLoGo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/football-player.png"))); // NOI18N

        javax.swing.GroupLayout pannelOverviewLayout = new javax.swing.GroupLayout(pannelOverview);
        pannelOverview.setLayout(pannelOverviewLayout);
        pannelOverviewLayout.setHorizontalGroup(
            pannelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelOverviewLayout.createSequentialGroup()
                .addGroup(pannelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannelOverviewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelOverviewLayout.createSequentialGroup()
                        .addContainerGap(82, Short.MAX_VALUE)
                        .addComponent(lblLoGo)
                        .addGap(52, 52, 52)))
                .addComponent(panelSumari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        pannelOverviewLayout.setVerticalGroup(
            pannelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelOverviewLayout.createSequentialGroup()
                .addGroup(pannelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannelOverviewLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelSumari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pannelOverviewLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lblLoGo)
                        .addGap(18, 18, 18)
                        .addComponent(lblName)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CLub Overview", pannelOverview);

        pannelPlayer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Full Name");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Number");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Date Born");

        btnInsertImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/icon_open.png"))); // NOI18N
        btnInsertImage.setText("Insert Image");
        btnInsertImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertImageActionPerformed(evt);
            }
        });

        btnCreate.setText("Create new player");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tblPlayer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlayerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPlayer);

        javax.swing.GroupLayout pannelPlayerLayout = new javax.swing.GroupLayout(pannelPlayer);
        pannelPlayer.setLayout(pannelPlayerLayout);
        pannelPlayerLayout.setHorizontalGroup(
            pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelPlayerLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannelPlayerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateBorn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pannelPlayerLayout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate)))
                .addGap(18, 18, 18)
                .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertImage, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage))
                .addGap(113, 113, 113))
            .addComponent(jScrollPane1)
        );
        pannelPlayerLayout.setVerticalGroup(
            pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelPlayerLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannelPlayerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateBorn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreate)
                            .addGroup(pannelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDelete)
                                .addComponent(btnEdit)
                                .addComponent(btnClear)))
                        .addGap(20, 20, 20))
                    .addGroup(pannelPlayerLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnInsertImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Club Player", pannelPlayer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String path ="imagestore\\player.png";
    private void btnInsertImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("imagestore");
        fileChooser.addChoosableFileFilter(new ImageFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);

        int option = fileChooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            path = file.getAbsolutePath();
            ImageIcon imgThisImg = new ImageIcon(new ImageIcon(path).getImage()
                .getScaledInstance(128, 128, Image.SCALE_SMOOTH));
            lblImage.setIcon(imgThisImg);
        }
    }//GEN-LAST:event_btnInsertImageActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:

        Connection con = new ConnectDB().createConn();
        String sqlCreate="insert into football_player(IDCLB,PLNAME,DAY_BORN,SCORE,YELLOWCARD,REDCARD"
        + ",PIC,NUMBER) values(?,?,?,0,0,0,?,?)";
        String sqlUpdateClub="update club set SLTV=? where idclb=?";
        try{
            PreparedStatement pre= con.prepareStatement(sqlCreate,ResultSet.TYPE_SCROLL_SENSITIVE
                ,ResultSet.CONCUR_UPDATABLE);
            pre.setInt(1, idCLB);
            pre.setString(2, txtFullName.getText());
            DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            pre.setString(3, df.format(DateBorn.getDate()));
            pre.setString(4, path);
            pre.setString(5, txtNumber.getText());
            pre.executeUpdate();

            JOptionPane.showMessageDialog(null,"Thêm dữ liệu thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            LoadPlayer(idCLB);
            pre=con.prepareStatement(sqlUpdateClub,ResultSet.TYPE_SCROLL_SENSITIVE
                ,ResultSet.CONCUR_UPDATABLE);
            pre.setInt(1, tblPlayer.getRowCount());
            pre.setInt(2, idCLB);
            pre.executeUpdate();
            con.close();

        }
        catch(SQLException e){
            e.printStackTrace();
            System.out.println("Lỗi create player");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        Connection con = new ConnectDB().createConn();
        String sqlAddPL="update football_player set PLNAME=?,PIC=?,NUMBER=?,DAY_BORN=? where idpl=?";
        try{
            PreparedStatement pre= con.prepareStatement(sqlAddPL,ResultSet.TYPE_SCROLL_SENSITIVE,
                ResultSet.CONCUR_UPDATABLE);
            pre.setString(1, txtFullName.getText());
            pre.setString(2, path);
            pre.setString(3, txtNumber.getText());
            DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            pre.setString(4, df.format(DateBorn.getDate()));
            pre.setString(3, txtNumber.getText());
            pre.setInt(5, PLSelected);
            pre.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null,"Sửa dữ liệu thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            LoadPlayer(idCLB);

        }
        catch(SQLException e){
            e.printStackTrace();
            System.out.println("Lỗi edit player");

        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,"Sure? You want to delete?", "Swing Tester",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            Connection con = new ConnectDB().createConn();
            String sqlCreate="delete from football_player where idpl=?";
            String sqlUpdateClub="update club set SLTV=? where idclb=?";
            try{
                PreparedStatement pre= con.prepareStatement(sqlCreate,ResultSet.TYPE_SCROLL_SENSITIVE
                    ,ResultSet.CONCUR_UPDATABLE);
                pre.setInt(1, PLSelected);
                pre.executeUpdate();

                JOptionPane.showMessageDialog(null,"Xoá dữ liệu thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                LoadPlayer(idCLB);
                pre=con.prepareStatement(sqlUpdateClub,ResultSet.TYPE_SCROLL_SENSITIVE
                    ,ResultSet.CONCUR_UPDATABLE);
                pre.setInt(1, tblPlayer.getRowCount());
                pre.setInt(2, idCLB);
                pre.executeUpdate();
                con.close();

            }
            catch(SQLException e){
                e.printStackTrace();
                System.out.println("Lỗi delete player");
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtFullName.setEditable(true);
        txtFullName.setText("");
        txtNumber.setText("");
        DateBorn.setDate(null);
        ImageIcon imgThisImg = new ImageIcon(new ImageIcon("imagestore\\player.png").getImage()
            .getScaledInstance(123, 128, Image.SCALE_SMOOTH));
        lblImage.setIcon(imgThisImg);
    }//GEN-LAST:event_btnClearActionPerformed

    int PLSelected;
    private void tblPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlayerMouseClicked
        // TODO add your handling code here:
        int indexTB=tblPlayer.getSelectedRow();
                Player pl =listPL.LayThongTin(indexTB);
                PLSelected=pl.getIDpl();
                txtFullName.setText(pl.getPlname());
                if(pl.getPic()==null){
                    ImageIcon imgThisImg = new ImageIcon(new ImageIcon("imagestore\\player.png").getImage()
                .       getScaledInstance(128, 128, Image.SCALE_SMOOTH));
                    lblImage.setIcon(imgThisImg);
                }
                else{
                    ImageIcon imgThisImg = new ImageIcon(new ImageIcon(pl.getPic()).getImage()
                    .getScaledInstance(128, 128, Image.SCALE_SMOOTH));
                    lblImage.setIcon(imgThisImg);
                }
                
                txtNumber.setText(pl.getNumber());
                if(pl.getDate_born()!=null){
                        try{
                        String sDate1=pl.getDate_born();
                        Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(sDate1);  
                        DateBorn.setDate(date1);
                    }
                    catch(Exception e){
                        e.printStackTrace();
                    }
                }
                else
                    DateBorn.setDate(null);
                if(pl.getPlname()!=null){
                    txtFullName.setEditable(false);
                }
                else
                    txtFullName.setEditable(true);
    }//GEN-LAST:event_tblPlayerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClubPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClubPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClubPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClubPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClubPage(idCLB).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateBorn;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInsertImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCard;
    private javax.swing.JLabel lblGoal;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLoGo;
    private javax.swing.JLabel lblMVP;
    private javax.swing.JLabel lblMember;
    private javax.swing.JLabel lblMostCard;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lblSBT;
    private javax.swing.JLabel lblST;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblYellow;
    private javax.swing.JPanel panelGoal;
    private javax.swing.JPanel panelMember;
    private javax.swing.JPanel panelMostGoal;
    private javax.swing.JPanel panelRed;
    private javax.swing.JPanel panelSBT;
    private javax.swing.JPanel panelST;
    private javax.swing.JPanel panelSumari;
    private javax.swing.JPanel panelYellow;
    private javax.swing.JPanel pannelOverview;
    private javax.swing.JPanel pannelPlayer;
    private javax.swing.JTable tblPlayer;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables

    public void LoadListclb(int idclb){
        listPL.listPlayer.removeAll(listPL.listPlayer);
        Connection con=new ConnectDB().createConn();
        String sqlClub="select * from football_player where idclb=?";
        try{
            PreparedStatement pre= con.prepareStatement(sqlClub,ResultSet.TYPE_SCROLL_SENSITIVE, 
                        ResultSet.CONCUR_UPDATABLE);
            pre.setInt(1, idclb);
            ResultSet rs= pre.executeQuery();
            while(rs.next()){
                Player player= new Player();
                player.setIDclb(idclb);
                player.setIDpl(Integer.parseInt(rs.getString("idpl")));
                player.setPic(rs.getString("pic"));
                player.setDate_born(rs.getString("DAY_BORN"));
                player.setNumber(rs.getString("number"));
                player.setPlname(rs.getString("plname"));
                player.setScore(rs.getInt("SCORE"));
                player.setYellow(rs.getInt("YELLOWCARD"));
                player.setRed(rs.getInt("REDCARD"));
                listPL.listPlayer.add(player);
            }
            con.close();
        }
        catch(SQLException e){
            e.printStackTrace();
            System.out.println("Lỗi load club");
        }
    }
     DefaultTableModel tblmodelPlayer;
    public void LoadPlayer(int clbid) {
                //tạo tablemodel và custom header
        LoadListclb(clbid);
        tblmodelPlayer = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        String tieude[]={"IDPL","Picture","Name","Date born","Number","Score","Yellow","Red"};
        tblmodelPlayer.setColumnIdentifiers(tieude);
        JTableHeader tableHeader = tblPlayer.getTableHeader();
        Font headerFont = new Font("Serif", Font.PLAIN, 14);
        tableHeader.setFont(headerFont);
        for(Player s: listPL.listPlayer){
            Object row[]=new Object[8];
            row[0]="PL"+s.getIDpl();
            if(s.getPic()==null){
                row[1]="imagestore\\player.png";
            }
            else
                row[1]=s.getPic();
            
            row[2]=s.getPlname();
            row[4]=s.getNumber();
            row[3]=s.getDate_born();
            row[5]=s.getScore();
            row[6]=s.getYellow();
            row[7]=s.getRed();
            tblmodelPlayer.addRow(row);
        }
        //set model cho table
        tblPlayer.setBackground(Color.WHITE);
        tblPlayer.setModel(tblmodelPlayer);
        tblPlayer.setFont(new Font("Serif", Font.PLAIN, 14));
        tblPlayer.setRowHeight(64);
        TableColumnModel columnModel = tblPlayer.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(70);
        columnModel.getColumn(1).setPreferredWidth(64);
        columnModel.getColumn(2).setPreferredWidth(250);
        columnModel.getColumn(3).setPreferredWidth(130);
        columnModel.getColumn(4).setPreferredWidth(70);
        columnModel.getColumn(5).setPreferredWidth(70);
        columnModel.getColumn(6).setPreferredWidth(70);
        columnModel.getColumn(7).setPreferredWidth(70);
        tblPlayer.getColumnModel().getColumn(1).setCellRenderer(new TableRenderer());
        this.setVisible(true);
    }

    private void LoadClubOverview(int clbid) {
        Connection con = new ConnectDB().createConn();
        String getClub="Select * from club where idclb= ?";
        try{
            PreparedStatement pre= con.prepareStatement(getClub,ResultSet.TYPE_SCROLL_SENSITIVE, 
                        ResultSet.CONCUR_UPDATABLE);
            pre.setInt(1, clbid);
            ResultSet rs= pre.executeQuery();
            while(rs.next()){
                lblMember.setText(rs.getString("sltv"));
                lblGoal.setText(rs.getString("bt"));
                lblSBT.setText(rs.getString("sltv"));
                lblName.setText(rs.getString("clbname"));
                ImageIcon imgThisImg = new ImageIcon(new ImageIcon(rs.getString("logo")).getImage()
                    .getScaledInstance(128, 128, Image.SCALE_SMOOTH));
                lblLoGo.setIcon(imgThisImg);
                lblST.setText(rs.getString("st"));
                lblSBT.setText(rs.getString("sbt"));
            }
            String card="select sum(yellowcard),sum(redcard) from football_player where idclb=?";
            pre=con.prepareStatement(card,ResultSet.TYPE_SCROLL_SENSITIVE, 
                        ResultSet.CONCUR_UPDATABLE);
            pre.setInt(1, clbid);
            rs= pre.executeQuery();
            while(rs.next()){
                lblRed.setText(rs.getString("sum(redcard)"));
                lblYellow.setText(rs.getString("sum(yellowcard)"));
            }
            String bestscore="select score,PLNAME from football_player where idclb=? order by score desc LIMIT 1";
            pre=con.prepareStatement(bestscore,ResultSet.TYPE_SCROLL_SENSITIVE, 
                        ResultSet.CONCUR_UPDATABLE);
            pre.setInt(1, clbid);
            rs= pre.executeQuery();
            while(rs.next()){
                if(Integer.parseInt(rs.getString("score"))==0){
                    break;
                }
                lblScore.setText(rs.getString("score"));
                lblMVP.setText(rs.getString("plname"));
            }
            String mostcard="SELECT PLNAME,(REDCARD*2 + YELLOWCARD) FROM football_player where IDCLB=? order by (REDCARD*2 + YELLOWCARD) desc limit 1;";
            pre=con.prepareStatement(mostcard,ResultSet.TYPE_SCROLL_SENSITIVE, 
                        ResultSet.CONCUR_UPDATABLE);
            pre.setInt(1, clbid);
            rs= pre.executeQuery();
            while(rs.next()){
                if(Integer.parseInt(rs.getString("(REDCARD*2 + YELLOWCARD)"))==0){
                    break;
                }
                lblMostCard.setText(rs.getString("PLNAME"));
                lblCard.setText(rs.getString("(REDCARD*2 + YELLOWCARD)"));
            }
            
            con.close();
        }
        catch(SQLException e){
            e.printStackTrace();
            System.out.println("Lỗi load overview");
        }
        
    }
}
