/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SoccerManagermentUIdelegate;

import java.awt.SystemColor;
import java.sql.*;
import SoccerManagementModel.*;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
/**
 *
 * @author Administrator
 */
public class CreateTour extends javax.swing.JFrame {
    static int tourid;
    /**
     * Creates new form CreateTour
     */
    public CreateTour(int tourid) {
        setTitle("Create Tournament");
        setVisible(true);
        initComponents();
        System.out.println(tourid);
        Date date=new Date();
        TimeEnd.setDate(date);
        TimeStart.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        txtOrganizer = new javax.swing.JTextField();
        txtTourName = new javax.swing.JTextField();
        txtStadium = new javax.swing.JTextField();
        txtSL = new javax.swing.JTextField();
        TimeStart = new com.toedter.calendar.JDateChooser();
        TimeEnd = new com.toedter.calendar.JDateChooser();
        cbRoundKicks = new javax.swing.JComboBox<>();
        lblLOGO = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        lblNumMatch = new javax.swing.JLabel();
        btnCreat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelMain.setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/previous.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtOrganizer.setBorder(javax.swing.BorderFactory.createTitledBorder("Organizer"));

        txtTourName.setBorder(javax.swing.BorderFactory.createTitledBorder("Tournament Name"));

        txtStadium.setBorder(javax.swing.BorderFactory.createTitledBorder("Stadium"));

        txtSL.setBorder(javax.swing.BorderFactory.createTitledBorder("Number Of Teams [6-104]"));
        txtSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLActionPerformed(evt);
            }
        });

        TimeStart.setBackground(new java.awt.Color(255, 255, 255));
        TimeStart.setBorder(javax.swing.BorderFactory.createTitledBorder("Time Start"));
        TimeStart.setForeground(new java.awt.Color(255, 255, 255));
        TimeStart.setDateFormatString("yyyy-MM-dd");

        TimeEnd.setBackground(new java.awt.Color(255, 255, 255));
        TimeEnd.setBorder(javax.swing.BorderFactory.createTitledBorder("Time End"));
        TimeEnd.setForeground(new java.awt.Color(255, 255, 255));
        TimeEnd.setDateFormatString("yyyy-MM-dd");

        cbRoundKicks.setForeground(new java.awt.Color(255, 255, 255));
        cbRoundKicks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        cbRoundKicks.setBorder(javax.swing.BorderFactory.createTitledBorder("Number Of Round Kicks"));
        cbRoundKicks.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRoundKicksItemStateChanged(evt);
            }
        });

        lblLOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/football-player.png"))); // NOI18N

        btnImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/icon_open.png"))); // NOI18N
        btnImage.setText("Insert Image");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        lblNumMatch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumMatch.setForeground(new java.awt.Color(0, 102, 102));
        lblNumMatch.setText("Number matchs of Tournament:  1");

        btnCreat.setBackground(new java.awt.Color(0, 255, 153));
        btnCreat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreat.setForeground(new java.awt.Color(255, 255, 255));
        btnCreat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagestore/Create.png"))); // NOI18N
        btnCreat.setText("Create Tournament");
        btnCreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbRoundKicks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTourName, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(txtOrganizer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStadium, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnImage, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                            .addComponent(lblNumMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addComponent(TimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCreat, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImage)
                    .addComponent(txtTourName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(txtOrganizer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtStadium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLOGO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbRoundKicks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNumMatch)
                .addGap(18, 18, 18)
                .addComponent(btnCreat)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatActionPerformed
        // TODO add your handling code here:
        Connection con=new ConnectDB().createConn();
        String sql= "insert into tournament(tnmname,sl,organizational,stadium,timestart,timeend,logo,roundkick,matchnum) values(?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement pre=con.prepareStatement(sql);
            pre.setString(1, txtTourName.getText());
            pre.setString(2, txtSL.getText());
            pre.setString(3, txtOrganizer.getText());
            pre.setString(4, txtStadium.getText());
            DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            pre.setString(5, df.format(TimeStart.getDate()));
            pre.setString(6, df.format(TimeEnd.getDate()));
            pre.setString(7, path);
            pre.setString(8,cbRoundKicks.getItemAt(cbRoundKicks.getSelectedIndex()));
            pre.setInt(9,sotran);
            pre.executeUpdate();
            
            con.close();
        }
        catch(SQLException e){
            e.printStackTrace();
            System.out.println("Lỗi create tournament");
        }
        
        this.setVisible(false);
        new StartingPage().setVisible(true);
    }//GEN-LAST:event_btnCreatActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StartingPage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    String path ="C:\\Users\\Administrator\\Documents\\NetBeansProjects\\Soccer-Management\\src\\imageInsert\\football-player.png";
    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
            JFileChooser fileChooser = new JFileChooser("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\Soccer-Management\\src\\imageInsert");
            fileChooser.addChoosableFileFilter(new ImageFilter());
            fileChooser.setAcceptAllFileFilterUsed(false);

            int option = fileChooser.showOpenDialog(this);
            if(option == JFileChooser.APPROVE_OPTION){
               File file = fileChooser.getSelectedFile();
               path = file.getAbsolutePath();
               ImageIcon imgThisImg = new ImageIcon(path);
               lblLOGO.setIcon(imgThisImg);
            }
            
    }//GEN-LAST:event_btnImageActionPerformed
    int sotran;
    private void cbRoundKicksItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRoundKicksItemStateChanged
        // TODO add your handling code here:
         LoadNumMatch();
        }

    private void LoadNumMatch() {
        int rk= Integer.parseInt(cbRoundKicks.getItemAt(cbRoundKicks.getSelectedIndex()));
        int number=Integer.parseInt(txtSL.getText());
        if(number%4==0){
            sotran=12*(number/4)*rk;
            lblNumMatch.setText("Number matchs of Tournament:  "+sotran);
        }
        else {
            sotran=12*(number/4)*rk+6*rk;
            lblNumMatch.setText("Number matchs of Tournament:  "+sotran);    }
        
    }//GEN-LAST:event_cbRoundKicksItemStateChanged

    private void txtSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLActionPerformed
        // TODO add your handling code here:
        int num;
        if(txtSL.getText().equals("0")==true)
            num=0;
        else
            num= Integer.parseInt(txtSL.getText());
        if(num%4==0||num%4==3)
            LoadNumMatch();
        else
            JOptionPane.showMessageDialog(null,"Số đội phải chia hết cho 4 hoặc chia 4 dư 3","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_txtSLActionPerformed
                class ImageFilter extends FileFilter {
           public final static String JPEG = "jpeg";
           public final static String JPG = "jpg";
           public final static String GIF = "gif";
           public final static String TIFF = "tiff";
           public final static String TIF = "tif";
           public final static String PNG = "png";

           @Override
           public boolean accept(File f) {
              if (f.isDirectory()) {
                 return true;
              }

              String extension = getExtension(f);
              if (extension != null) {
                 if (extension.equals(TIFF) ||
                    extension.equals(TIF) ||
                    extension.equals(GIF) ||
                    extension.equals(JPEG) ||
                    extension.equals(JPG) ||
                    extension.equals(PNG)) {
                    return true;
                 } else {
                    return false;
                 }
              }
              return false;
           }

           @Override
           public String getDescription() {
              return "Image Only";
           }

           String getExtension(File f) {
              String ext = null;
              String s = f.getName();
              int i = s.lastIndexOf('.');

              if (i > 0 &&  i < s.length() - 1) {
                 ext = s.substring(i+1).toLowerCase();
              }
              return ext;
           } 
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTour(tourid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser TimeEnd;
    private com.toedter.calendar.JDateChooser TimeStart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreat;
    private javax.swing.JButton btnImage;
    private javax.swing.JComboBox<String> cbRoundKicks;
    private javax.swing.JLabel lblLOGO;
    private javax.swing.JLabel lblNumMatch;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField txtOrganizer;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtStadium;
    private javax.swing.JTextField txtTourName;
    // End of variables declaration//GEN-END:variables
}
